### ISSUE TITLE
Store "reason" in ordermeta

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-reason-for-cancelling#16]
v2.5+ of Paid Memberships Pro introduces the `pmpro_membership_ordermeta` table. We should update this Add On to store the user's entered "reason" in the last order's ordermeta. 

We would need to check the version of PMPro and make sure that the table is available before completely migrating to this method as the only place the data is stored. We can make the update to save the data in two places for perhaps 1 year then update to only store in ordermeta.

**Comment by dparker1005** [comment]
#29 will store the value in user meta, which is more flexible than order meta.
