### ISSUE TITLE
Reguest - log reason

### ISSUE THREAD

**Issue by smadds** [strangerstudios/pmpro-reason-for-cancelling#2]
Would it be possible to log the reason to the usermeta table in order to capture the information for later review?

**Comment by hbcondo** [comment]
I second this. Per the [member support forum](https://www.paidmembershipspro.com/forums/topic/could-not-cancel-old-subscription-3/), there are instances where PMP doesn't send out e-mails so the cancellation reason is lost.

**Comment by andrewlimaza** [comment]
Here you go - https://github.com/strangerstudios/pmpro-reason-for-cancelling/pull/4

Still needs to be thoroughly tested before being merged in.
