### ISSUE TITLE
Cancels permanently if you reload the canceled page

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-reason-for-cancelling#25]
When a user with a recurring subscription, candles their subscription, they are given their end date.

If they then reload this page, the user cancels the account totally.

https://www.loom.com/share/f3583d8547d247fdb17b040c54b94556

We could add a check "If the user has an expiration date, don’t cancel" on the confirmation page?

**Comment by kimcoleman** [comment]
I believe the addition of a nonce in the current release will prevent this. Closing until we hear new reports of this issue.
