### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error - v1.3

### ISSUE THREAD

**Issue by hbcondo** [strangerstudios/pmpro-reason-for-cancelling#9]
I'm trying to install v.1.3 2020-01-14 per the installation instructions in the [readme](https://github.com/strangerstudios/pmpro-reason-for-cancelling/blob/master/readme.txt) but receive the following error:

![image](https://user-images.githubusercontent.com/306958/72962254-b02f3b80-3d68-11ea-9795-cc432293f2fd.png)

> Plugin could not be activated because it triggered a fatal error.

`Fatal error: Cannot redeclare pmpror4c_init() (previously declared in /srv/htdocs/wp-content/plugins/pmpro-reason-for-cancelling/pmpro-reason-for-cancelling.php:25) in /srv/htdocs/wp-content/plugins/pmpro-reason-for-cancelling-master/pmpro-reason-for-cancelling.php on line 29`

We were successfully running the previous version without issues.

**Comment by andrewlimaza** [comment]
Hi @hbcondo 

The issue seems to be that you already have the reason for cancelling plugin installed. Your one version was downloaded from Github as it has `-master` in the plugin folder name and this is treated as a separate plugin. (But the code is identical, WordPress treats it as a separate plugin).

**Comment by andrewlimaza** [comment]
You should remove the `-master` from the folder name and merge it into the existing folder that's already there. If you have a Plus license for Paid Memberships Pro you are able to update it via the WordPress dashboard automatically.
